language: python

matrix:
  include:
  - python: 2.6
    env: TOXENV=py26-test,py26-wsgi,py26-flask
    install: travis_retry pip install coveralls 'tox<3' 'idna<2.8' 'pycparser<2.19'
    dist: trusty

  - python: "2.7_with_system_site_packages"
    env: TOXENV=py27-test
  - python: 2.7
    env: TOXENV=py27-test,py27-requests,py27-wsgi,py27-flask,py27-django18-migrate1-django1,py27-django19-migrate1-django1,py27-django110-migrate1-django1,py27-django111-migrate1-django1,py27-tornado

  - python: 3.3
    install:
    - travis_retry pip install coveralls 'virtualenv<16'
    - pip install 'tox<3' 'pluggy<0.6.0' nose-cov webtest
    script:
      - TOXENV=py33-test,py33-requests,py33-wsgi,py33-flask,py33-tornado tox
    dist: trusty

  - python: 3.4
    env: TOXENV=py34-test,py34-requests,py34-wsgi,py34-flask,py34-tornado

  - python: 3.5
    env: TOXENV=py35-test,py35-requests,py35-wsgi,py35-flask,py35-django18-migrate1-django1,py35-django19-migrate1-django1,py35-django110-migrate1-django1,py35-django111-migrate1-django1,py35-tornado

  - python: 3.6
    env: TOXENV=py36-test,py36-requests,py36-asgi,py36-wsgi,py36-flask,py36-django18-migrate1-django1,py36-django19-migrate1-django1,py36-django110-migrate1-django1,py36-django111-migrate1-django1,py36-django20-migrate1-django1,py36-django21-migrate1-django1,py36-tornado

  - python: 3.7
    env: TOXENV=py37-test,py37-requests,py37-asgi,py37-wsgi,py37-flask,py37-django18-migrate1-django1,py37-django19-migrate1-django1,py37-django110-migrate1-django1,py37-django111-migrate1-django1,py37-django20-migrate1-django1,py37-django21-migrate1-django1,py37-tornado

  - python: 3.8
    env: TOXENV=py38-test,py38-requests,py38-asgi,py38-wsgi,py38-flask,py38-django18-migrate1-django1,py38-django111-migrate1-django1,py38-django20-migrate1-django1,py38-django21-migrate1-django1,py38-tornado,py38-lint

install:
  - travis_retry pip install coveralls tox

script:
  - tox

after_success:
  - coveralls

before_deploy:
  - sudo apt-get update
  - sudo make deb-bootstrap
  - make deb-build
  - mv deb_dist/python-bugsnag_*.deb deb_dist/python-bugsnag.deb

deploy:
  provider: releases
  api_key:
    secure: "JM/zSJAowC1jFKdjk88Um+S/t/OKhqx9Yw7xCfk9INy683z9e8U1z8dIwen+XIFbS+o2JKamU1zL3rZbgOiDQPWetl5cyZCuErzZBmOsegjZTc2ZazQdO90jxYxcnP0faQO9W00uagSDe4NmYoi2dJKSdtKExOzdHDF3qjkLSUc="
  file: deb_dist/python-bugsnag.deb
  skip_cleanup: true
  on:
    tags: true
    python: "2.7_with_system_site_packages"
    condition: "$TOXENV = py27-test"
