language: python

matrix:
  include:
  - python: 2.6
    env: TOXENV=py26-test
    install: travis_retry pip install coveralls 'tox<3' 'idna<2.8' 'pycparser<2.19'
  - python: 2.6
    env: TOXENV=py26-requests-test
    install: travis_retry pip install coveralls 'tox<3' 'idna<2.8' 'pycparser<2.19'
  - python: 2.6
    env: TOXENV=py26-wsgi
    install: travis_retry pip install coveralls 'tox<3' 'idna<2.8' 'pycparser<2.19'
  - python: 2.6
    env: TOXENV=py26-flask
    install: travis_retry pip install coveralls 'tox<3' 'idna<2.8' 'pycparser<2.19'

  - python: "2.7_with_system_site_packages"
    env: TOXENV=py27-test
  - python: 2.7
    env: TOXENV=py27-test
  - python: 2.7
    env: TOXENV=py27-requests-test
  - python: 2.7
    env: TOXENV=py27-wsgi
  - python: 2.7
    env: TOXENV=py27-flask
  - python: 2.7
    env: TOXENV=py27-django18-migrate1-django1
  - python: 2.7
    env: TOXENV=py27-django19-migrate1-django1
  - python: 2.7
    env: TOXENV=py27-django110-migrate1-django1
  - python: 2.7
    env: TOXENV=py27-django111-migrate1-django1

  - python: 3.3
    install:
    - travis_retry pip install coveralls 'virtualenv<16'
    - virtualenv venv --no-wheel --no-download
    - source venv/bin/activate
    - pip install -r dev_requirements.txt
    - pip install webtest # For WSGI
    script: nosetests --tests=tests integrations/test_wsgi.py -sv --with-coverage --cover-package=bugsnag

  - python: 3.4
    env: TOXENV=py34-test
  - python: 3.4
    env: TOXENV=py34-requests-test
  - python: 3.4
    env: TOXENV=py34-wsgi

  - python: 3.5
    env: TOXENV=py35-test
  - python: 3.5
    env: TOXENV=py35-requests-test
  - python: 3.5
    env: TOXENV=py35-wsgi
  - python: 3.5
    env: TOXENV=py35-django18-migrate1-django1
  - python: 3.5
    env: TOXENV=py35-django19-migrate1-django1
  - python: 3.5
    env: TOXENV=py35-django110-migrate1-django1
  - python: 3.5
    env: TOXENV=py35-lint

  - python: 3.6
    env: TOXENV=py36-test
  - python: 3.6
    env: TOXENV=py36-requests-test
  - python: 3.6
    env: TOXENV=py36-wsgi
  - python: 3.6
    env: TOXENV=py36-django18-migrate1-django1
  - python: 3.6
    env: TOXENV=py36-django19-migrate1-django1
  - python: 3.6
    env: TOXENV=py36-django110-migrate1-django1
  - python: 3.6
    env: TOXENV=py36-django111-migrate1-django1
  - python: 3.6
    env: TOXENV=py36-django20-migrate1-django1
  - python: 3.6
    env: TOXENV=py36-django21-migrate1-django1
  - python: 3.6
    env: TOXENV=py36-lint

install: travis_retry pip install coveralls tox

script:
  - tox

after_success:
  - coveralls

before_deploy:
  - sudo apt-get update
  - sudo make deb-bootstrap
  - make deb-build
  - mv deb_dist/python-bugsnag_*.deb deb_dist/python-bugsnag.deb
deploy:
  provider: releases
  api_key:
    secure: "JM/zSJAowC1jFKdjk88Um+S/t/OKhqx9Yw7xCfk9INy683z9e8U1z8dIwen+XIFbS+o2JKamU1zL3rZbgOiDQPWetl5cyZCuErzZBmOsegjZTc2ZazQdO90jxYxcnP0faQO9W00uagSDe4NmYoi2dJKSdtKExOzdHDF3qjkLSUc="
  file: deb_dist/python-bugsnag.deb
  skip_cleanup: true
  on:
    tags: true
    python: "2.7_with_system_site_packages"
    condition: "$TOXENV = py27-test"
